sudo: true

services:
  - docker

matrix:
  include:
    - language: python
      python: 2.7
      install:
        - sudo ./install-travis.sh
      script:
        - sudo ./test-travis.sh
    - language: python
      python: 3.6
      install:
        - sudo source install-travis.sh
      script:
        - sudo source test-travis.sh
    - language: r
      dist: trusty
      cache: packages
      r_packages:
        - covr
      before_install:
        - export NOT_CRAN=true
        - export MLFLOW_TEST_REQUIREMENTS=false
        - sudo source install-travis.sh
        - export MLFLOW_HOME=$(pwd)
        - cd R/mlflow
      script:
        - R CMD build .
        - R CMD check --no-build-vignettes --no-manual --no-tests cloudml*tar.gz
        - cd tests
        - export LINTR_COMMENT_BOT=false
        - Rscript ../.travis.R
      after_success:
        - Rscript -e 'covr::codecov()'
